// Copyright (c) 2017-2023, University of Tennessee. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This program is free software: you can redistribute it and/or modify it under
// the terms of the BSD 3-Clause license. See the accompanying LICENSE file.

#ifndef BLAS_DEFINES_H
#define BLAS_DEFINES_H

// auto-generated by: 
// /usr/bin/cmake 3.20.2
// host: wave8-login3.wave.scu.edu
//
// Definitions for:
// CXX   = 
//         /WAVE/apps/el8/eb/software/GCCcore/12.3.0/bin/c++
// LIBS  = 
//         /WAVE/projects/ycho_lab/software/OpenBLAS-GCC_12.3.0/lib/libopenblas.so

#define BLAS_FORTRAN_ADD_
#define BLAS_HAVE_OPENBLAS
#define BLAS_HAVE_CBLAS


#endif        //  #ifndef BLAS_DEFINES_H
